### ISSUE TITLE
Template value errors in sensor.shf_control_factor_1, sensor.shf_electricity_price_now

### ISSUE THREAD

**Issue by vikohub** [T3m3z/spotprices2ha#10]
Just updated to 0.1.10.
After restart, found the below in logs:

Logger: homeassistant.helpers.template_entity
Source: helpers/template_entity.py:364 
First occurred: 10:30:09 (17 occurrences) 
Last logged: 10:30:09

TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ (states("sensor.shf_control_factor_1") | float /2 + 0.5) | default("Unknown") }}' but no default was specified') while processing template 'Template("{{ (states("sensor.shf_control_factor_1") | float /2 + 0.5) | default("Unknown") }}")' for attribute '_attr_native_value' in entity 'sensor.shf_control_factor_0_1'
TemplateError('TypeError: 'NoneType' object is not iterable') while processing template 'Template("{% set output = namespace(value=[]) %} {% for value in state_attr("sensor.shf_control_factor_1", "today_values") %} {% set output.value = output.value + [ value | float /2 + 0.5 ] %} {% endfor %} {{ output.value }}")' for attribute 'today_values' in entity 'sensor.shf_control_factor_0_1'
TemplateError('TypeError: 'NoneType' object is not iterable') while processing template 'Template("{% set output = namespace(value=[]) %} {% for pnow in state_attr("sensor.shf_electricity_price_now", "today_prices") %} {% set pmin = state_attr("sensor.shf_electricity_price_now", "today_min") | float %} {% set pmax = state_attr("sensor.shf_electricity_price_now", "today_max") | float %} {% set value = max(min((2*(pmax - pnow) / (pmax - pmin)-1) * states('input_number.shf_control_function_factor') | float,1),-1) %} {% if states("input_select.shf_control_function" ) == "Linear" %} {% set output.value = output.value + [value | round(2)] %} {% else %} {% set output.value = output.value + [sin(value*pi/2) | round(2)] %} {% endif %} {% endfor %} {{ output.value }}")' for attribute 'today_values' in entity 'sensor.shf_control_factor_1'
TemplateError('ValueError: Template error: int got invalid input 'unavailable' when rendering template '{% set value = state_attr("sensor.shf_electricity_price_now", "data")[states("sensor.shf_idx")|int+now().hour] %} {{ value["Rank"] <= states("input_number.shf_rank_slider") | int }}' but no default was specified') while processing template 'Template("{% set value = state_attr("sensor.shf_electricity_price_now", "data")[states("sensor.shf_idx")|int+now().hour] %} {{ value["Rank"] <= states("input_number.shf_rank_slider") | int }}")' for attribute '_state' in entity 'binary_sensor.shf_rank_acceptable'
TemplateError('UndefinedError: None has no element 10') while processing template 'Template("{% set value = state_attr("sensor.shf_electricity_price_now", "today_prices")[ now().hour ] %} {{ value <= states("input_number.shf_price_slider") | float }}")' for attribute '_state' in entity 'binary_sensor.shf_price_acceptable'

**Comment by T3m3z** [comment]
I have "a new beta version" of the code now available on a different branch. Maybe you could try this to see whether errors disappear.

So please check this branch (will be merged to master if no serious errors are found from the code so please report them using a new Issue if you find any): https://github.com/T3m3z/spotprices2ha/tree/v0.2.0-draft

**Comment by T3m3z** [comment]
Fixed by #21 .
