### ISSUE TITLE
Helpers have reset after Daylight Saving Time DST

### ISSUE THREAD

**Issue by luotinen** [T3m3z/spotprices2ha#13]
All the Helpers reset when DST occurs. How to reset the defaults or do you have a list somewhere so these can be entered manually? 

![kuva](https://user-images.githubusercontent.com/6695329/228138726-3da81ace-1f79-45fa-855f-200395a54793.png)

**Comment by T3m3z** [comment]
Hello!

In my instance I haven't seen this happening when DST happened. I will ask from some friends whether this has happened on their instance or not.

Anyway, all the inputs listed in your screenshot are meant to be altered by the user to match their own setup. So "my defaults" would most probably not match your use case.

**Comment by T3m3z** [comment]
No further comments in a long time so I'm going to close this. Please reopen this one (or a create new one referencing this issue) if the problem persists. I think that quite many would have reported this same problem if it was really DST related.
