### ISSUE TITLE
Yield overhead costs (selling electricity)

### ISSUE THREAD

**Issue by MarjoCo** [T3m3z/spotprices2ha#25]
Is there a way to have different overhead costs for buying and selling electricity? It seems to me that the overhead costs are added directly to the data and therefore there is now way to get the original stock-price if you have added the overhead electricity costs.

Would it be possible to have a sensor for original stock price, new input field for Yield overhead costs and then get the value + overhead costs as a total for Yield price now?

This would help in order to get the energy-dashboard working correctly and to make automations whether to sell your yielded electricity or to try to use it yourself.

**Comment by T3m3z** [comment]
Hello!

So basically you need a sensor indicating the current stock price with a different overhead costs? 

The easiest way for you to add this functionality would be to create a new template helper. That can be achieved by navigating to Settings -> Devices & Services -> Helpers -> Create Helper. Select "Template" and "Template a sensor". Add one of the following examples to field "State template".

If you need stock prices with 24% VAT included:
```
{{ (state_attr("sensor.shf_data", "data") | selectattr("Timestamp", "lt", now() | as_timestamp) | list)[-1]["PriceWithTax"] | round(4) + 0.123 }}
```

If you need stock prices without any taxes:
```
{{ (state_attr("sensor.shf_data", "data") | selectattr("Timestamp", "lt", now() | as_timestamp) | list)[-1]["PriceNoTax"] | round(4) + 0.123 }}
```

Just change 0.123 to match your overhead cost.

**Comment by MarjoCo** [comment]
Yes, you can. This worked for me!!! Thank you!
