### ISSUE TITLE
UI screenshots in README not up to date(?)

### ISSUE THREAD

**Issue by vikohub** [T3m3z/spotprices2ha#29]
Hi,
in the main README, it looks like  the screenshots following this text:
"Example of UI elements (grouping is not included in the package):"
are maybe not up to date with the features in the current release.

At least SHF Idx is no longer created by the spot-price.yaml - nor are the Cheapest period start & hours helpers.

**Comment by T3m3z** [comment]
Updated the screenshot to match current sensors.
