### ISSUE TITLE
Error loading configuration

### ISSUE THREAD

**Issue by iw5lime** [T3m3z/spotprices2ha#7]
New user here so if I miss something, I apologies.

Trying to install this. Checking the configuration via dev tool hits a message about invalid configuration

Error loading /config/configuration.yaml: mapping values are not allowed here
in "/config/spot-price.yaml", line 28, column 66

I'm using the following:
Home Assistant 2023.1.1
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230104.0 - latest

**Comment by T3m3z** [comment]
Hello!

Not sure why this is happening. I tried loading the newest version from this repository and it seemed to work well with Home Assistant 2022.12.7. I will try upgrading to 2023.1.1 to see whether this causes some problems.

**Comment by T3m3z** [comment]
Yeah, I upgraded to Home Assistant version 2023.1.1 and the current version of this spotprices2ha seems to be working OK. "Check Configuration" in Developer tools returns "Configuration will not prevent Home Assistant from starting!" so this should be OK too.

How did you install this "spot-prices.yaml" file? Did you copypaste the whole file or the contents of the file?

**Comment by iw5lime** [comment]
As always it was user's fault.  Something happened when copied the yaml from github. Copypasted contents of the file and all good. Thanks for help!
